<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
$config['base_url']	= '';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
//$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_+\&-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = '1234';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'web_session';
$config['sess_expiration']		= 60*10;//60*60*24;
$config['sess_expire_on_close']	= FALSE;
$config['sess_encrypt_cookie']	= TRUE;
$config['sess_use_database']	= TRUE;
$config['sess_table_name']		= 'sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';

error_reporting(0);

$config['upload_path_personal_information'] = "/Applications/MAMP/htdocs/rgsm/uploads/personal_information/";       // 人事資料

$config['personalInfo']['zh-hant']['gender']        = array(1=>'男', 2=>'女');
$config['personalInfo']['zh-hant']['nationality']   = array(1=>'台灣', 2=>'印尼', 3=>'越南');
$config['personalInfo']['zh-hant']['hasIdCard']     = array(1=>'本國身分證', 2=>'護照', 3=>'居留證', 4=>'其他國家身分證件');
$config['personalInfo']['zh-hant']['education']     = array(1=>'高中職以下', 2=>'高中職', 3=>'專科', 4=>'四技', 5=>'二技', 6=>'高中職', 7=>'大學', 8=>'碩士', 9=>'博士');
$config['personalInfo']['zh-hant']['study_status']  = array(1=>'就學中', 2=>'肄業');
$config['personalInfo']['zh-hant']['military_service_status'] = array(1=>'役畢', 2=>'服役中');
$config['personalInfo']['zh-hant']['disability_status'] = array(1=>'無', 2=>'輕度殘障', 3=>'中度殘障');
$config['personalInfo']['zh-hant']['pipeline']          = array(1=>'人才庫', 2=>'員工推薦', 3=>'內部員工', 4=>'Partner推薦', 5=>'員工推薦', 6=>'104人力銀行', 7=>'1111人力銀行', 8=>'其他人力銀行');
$config['personalInfo']['zh-hant']['language']          = array(1=>'台語', 2=>'英文', 3=>'德文', 4=>'俄文', 5=>'義大利文', 6=>'葡萄牙文', 7=>'阿拉伯文', 8=>'法文', 9=>'西班牙文', 10=>'印尼語', 11=>'馬來語', 12=>'粵語', 13=>'越語', 14=>'印度語', 15=>'日文');
$config['personalInfo']['zh-hant']['skill_level']       = array(1=>'精通', 2=>'中等', 3=>'略懂', 4=>'不會');
$config['personalInfo']['zh-hant']['design_skills']     = array(1=>'Sketch', 2=>'InVision', 3=>'Figma', 4=>'Photoshop', 5=>'PhotoImpact', 6=>'AutoCAD', 7=>'Maya', 8=>'Scrum', 9=>'Others');
$config['personalInfo']['zh-hant']['develope_skills']   = array(1=>'C++', 2=>'C#', 3=>'ASP', 4=>'PHP', 5=>'JSP', 6=>'ASP.NET', 7=>'ASP.NET Core', 8=>'Java', 9=>'Node.js', 10=>'Python', 11=>'Go', 12=>'AWS Cloud', 13=>'GCP Cloud', 14=>'Windows', 15=>'Linux', 16=>'Azure', 17=>'Ali Cloud', 18=>'Docker', 19=>'kubernetes', 20=>'MySQL', 21=>'MSSQL', 22=>'SqlLite', 23=>'Oracle', 24=>'Firebase', 25=>'MongoDB', 26=>'Cassandra', 27=>'GraphQL', 28=>'Machine Learning', 29=>'React', 30=>'Angular', 31=>'PostgreSQL', 32=>'CouchDB', 33=>'ES6', 34=>'ES5', 35=>'Symfony(PHP)', 36=>'Laravel(PHP)', 37=>'DJango', 38=>'Others');
$config['personalInfo']['zh-hant']['interest_industry'] = array(1=>'媒體和互聯網', 2=>'傳產製造業', 3=>'公共服務供應', 4=>'資訊科技業', 5=>'精密技工', 6=>'人力資源跟企劃', 7=>'資訊科技業', 8=>'精密技工', 9=>'人力資源跟企劃', 10=>'液壓專家', 11=>'物流倉儲業', 12=>'工業自動化', 13=>'媒體出版業', 14=>'運輸和物流', 15=>'精密儀器操作', 16=>'專業科學教學', 17=>'現場技術員電機工程', 18=>'醫療保健', 19=>'藝術、娛樂及休閒服務業', 20=>'執法', 21=>'商業/諮詢/管理');
$config['personalInfo']['zh-hant']['department']        = array(1=>'資工', 2=>'電機', 3=>'航太工程', 4=>'機械', 5=>'化工', 6=>'材料', 7=>'設計學類', 8=>'工程', 9=>'物理', 10=>'數學及統計學類', 11=>'遊戲設計', 12=>'化學', 13=>'生命科學學類', 14=>'建築及都市規劃學類', 15=>'農林食品科學學類', 16=>'運輸服務學類', 17=>'醫藥衛生學類', 18=>'運輸服務學類', 19=>'獸醫學類', 20=>'計算語言學', 21=>'環境保護學類', 22=>'機械電子學', 23=>'工藝技術員金屬冶金', 24=>'通訊工程', 25=>'動力機械群');
$config['personalInfo']['zh-hant']['job_application']   = array(1=>'人工智能（AI）/機器學習工程師', 2=>'資安工程師', 3=>'電腦研究工程師', 4=>'軟體開發工程師', 5=>'前端開發工程師', 6=>'後端開發工程師', 7=>'全端開發工程師', 8=>'DevOps工程師', 9=>'物流網工程師', 10=>'工業自動化工程', 11=>'系統分析師DBA', 12=>'軟體開發工程師', 13=>'Java 開發工程師', 14=>'電腦硬體工程師', 15=>'移動應用開發工程師', 16=>'Web Designer (UI/UX Designer)', 17=>'技術銷售工程師', 18=>'Python開發工程師', 19=>'網路系統工程師');

/* End of file config.php */
/* Location: ./application/config/config.php */
